### ISSUE TITLE
[BUG] Ajax not working while collecting

### ISSUE THREAD

**Issue by Janvier123** [matronator/GlobalCollapse#11]
**Describe the bug**
when pressing Collect on the buildings page, does NOT increase your
I keep pressing collect but its not adding anything

**To Reproduce**
click "collect"

**Expected behavior**

**Comment by matronator** [comment]
Are you sure it's not collecting? Do you mean it's not updating the values under the land card above your buildings? This one:

<img width="1126" alt="Snímek obrazovky 2021-07-23 v 18 11 32" src="https://user-images.githubusercontent.com/5470780/126810907-98b2c76f-1b9b-468d-aae6-518a97d8d2e0.png">

Because that's not supposed to update after collecting as it doesn't show your resources, but how much your buildings produce each collection round (every 5 hours). You should check your stash in the Darknet tab here:

<img width="1110" alt="Snímek obrazovky 2021-07-23 v 18 14 47" src="https://user-images.githubusercontent.com/5470780/126811267-daa6cdd0-dc7d-4127-ab0f-bb7fc0101277.png">

That one is showing your actual resources you have and it's updating the values correctly (just checked).

Was that it? If so, please don't close the issue yet, I'll change the tag to enhancement, because it is a bit confusing and needs some redesign to be more clear about what's shown where.

**Comment by matronator** [comment]
Solved in 5edb7322e04a2bdb2193c0c8a2b8f786af134ff0
