### ISSUE TITLE
[BUG] Darknet Page

### ISSUE THREAD

**Issue by tyfricko** [matronator/GlobalCollapse#19]
**Describe the bug**
Darknet Page is not getting any weed sellers and the prices didn't change

**To Reproduce**
1. Go to https://global-collapse.com/darknet
2. Click on any refresh button
3. Same seller but all with the same prices for the same drug

**Expected behavior**
Change in prices so we can buy low and sell high
Have at least one weed seller, because from the start of my journey I didn't see a weed seller and I have a lot of weed :)

**Screenshots**
https://freeimage.host/i/iHiDFa

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome, edge

**Comment by matronator** [comment]
Hi, the darknet offers are random. You can change the offer to a random new one by any of the following ways:

1. Buy out the vendor so he has no product left in stock
2. Sell to the vendor so that he has no money left
3. Click the refresh button (you can do this every hour)

And just hope for the best.
