### ISSUE TITLE
File 'app/config/config.local.neon' is missing or is not readable

### ISSUE THREAD

**Issue by wumix** [matronator/GlobalCollapse#5]
Nette\FileNotFoundException

File '/home/https://xxxx.tld/public_html/app/config/config.local.neon' is missing or is not readable. create file► search►

**Comment by matronator** [comment]
Thanks for reporting!
This is intentional, as `config.local.neon` contains sensitive information (read more here: [Nette Framework documentation](https://doc.nette.org/en/3.0/configuring)). I've created an example file in the `app/config` folder, follow the instructions in the file and it should work. You can find the example file here: [app/config/config.local.example.neon](https://github.com/matronator/GlobalCollapse/blob/master/app/config/config.local.example.neon)
